url = "https://localhost:8000"

SUPABASE_URL="https://hxmzmfwsrwebvbuvczoq.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bXptZndzcndlYnZidXZjem9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2OTU2MDEsImV4cCI6MjEwMjI3MTYwMX0.DA1JyqpcmbiATpmmf7wp_a4RBbZo9MyeoQBCoRZoKb8"


client_id = "421188872352-rtakin7ugspe3b1o6p6uqf2er4kna7fr.apps.googleusercontent.com"
client_secret = ""